### ISSUE TITLE
How to load the pdf file from stream or byte[]?

### ISSUE THREAD

**Issue by jasonlaw** [Dtronix/PDFiumCore#8]

**Comment by DorianRudolph** [comment]
I'm just evaluating this library for myself and it seems like you can use  `FPDF_LoadCustomDocument` or `FPDF_LoadMemDocument`.

**Comment by DJGosnell** [comment]
I've added a new test for this usage. 
https://github.com/Dtronix/PDFiumCore/blob/83177a58fe366f4fb61a27b680ad7836a96146b7/src/PDFiumCore.Tests/FpdfviewTests.cs#L35-L49
